### ISSUE TITLE
Native `VfsFile.write` memory leak.

### ISSUE THREAD

**Issue by Kesanov** [korlibs/korio#137] opened 2021-07-22 10:19 UTC
I am using the following code to write into a file:
```kotlin
class Empty(val n: Int): AsyncInputStream {
    override suspend fun close() {}
    override suspend fun read(buffer: ByteArray, offset: Int, len: Int): Int {
        for (i in 0 until len) buffer[i+offset] = 0
        return min(len, n - offset)
    }
}

localApplicationVfs["file.txt"].openUse(VfsOpenMode.APPEND) {
  Empty(500_000_000).consume(temp=ByteArray(0x100_000)) { data, ix, len ->
     write(data, ix, len)
  }
}
```
This should create a 500MB `file.txt` in constant memory. 
It does so on JVM. However, on Mingwx64 it consumes 500MB RAM instead.

**Comment by Josef-Vonasek** [comment] 2021-07-31 08:50
Fixed by adding `fflush`.

**Comment by soywiz** [comment] 2021-08-02 17:10
@Josef-Vonasek https://github.com/korlibs/korio/blob/e1ae02896db858ba043caf26aa49347e58e9e31e/korio/src/nativeCommonMain/kotlin/com/soywiz/korio/file/std/LocalVfsNative.kt#L125 did you put the `fflush` here? did that fixed the leak?

**Comment by Josef-Vonasek** [comment] 2021-08-09 11:35
Yes.

**Comment by soywiz** [comment] 2021-11-07 09:59
Can't reproduce anymore with latest korge-next master. Closing it

**Closed by soywiz** 2021-11-07 09:59 UTC
Labels: bug, check
