### ISSUE TITLE
Resource not found

### ISSUE THREAD

**Issue by dhakehurst** [korlibs/korio#27] opened 2019-02-20 15:10 UTC
import com.soywiz.korio.file.std.resourcesVfs is not finding the resource.

The scenario:
- module1 contains the resource
- test in module 1 finds the resource correctly

module2 depends on module1
- contains a main method
- calls a function on an object in module 1 that accesses the resource
- com.soywiz.korio.lang.InvalidOperationException: Can't find <file> in ResourcesVfsProviderJvm
running from InteliJ the error is different,
- java.io.FileNotFoundException: ....../module2/classes/kotlin/jvm8/main/<file>

seems that it is looking in the module2 classpath rather than the module1 classpath

**Comment by soywiz** [comment] 2019-02-20 15:16
Does this reproduce using gradle, or when executing main/tests on intelliJ?

**Comment by dhakehurst** [comment] 2019-02-21 12:29
I get
 'com.soywiz.korio.lang.InvalidOperationException: Can't find  in ResourcesVfsProviderJvm'
when I execute something built by gradle
and
' java.io.FileNotFoundException: ....../module2/classes/kotlin/jvm8/main/'
when running inside intelij

**Comment by dhakehurst** [comment] 2019-02-28 09:43
do you want/need some sample code to reproduce this?

**Comment by soywiz** [comment] 2019-02-28 09:51
If you can provide a minimal zip file reproducing it, that would indeed help a lot

**Comment by soywiz** [comment] 2020-05-01 10:58
I'm closing this since it has been more than a year and couldn't reproduce it, maybe fixed already. But feel free to reopen if it is no the case.

**Closed by soywiz** 2020-05-01 10:58 UTC
Labels: bug
